[[main]]
  name = "About"
  url = "/about/"
  weight = 10

[[main]]
  name = "Blog"
  url = "/blog/"
  weight = 20

[[main]]
  name = "Misc"
  url = "/blog/"
  parent = "Blog"
  weight = 30

[[main]]
  name = "Papers"
  url = "/papers/"
  parent = "Blog"
  weight = 30

[[main]]
  name = "Videos"
  url = "/media/"
  parent = "Blog"
  weight = 30



[[main]]
  name = "Projects"
  url = "/projects/"
  weight = 40
  

[[main]]
  name = "Sample project"
  url = "/en/projects/sample-project/"
  parent = "Projects"
  weight = 1

[[main]]
  name = "Another project"
  url = "/en/projects/another-project/"
  parent = "Projects"
  weight = 2

[[main]]
  name = "Tags"
  url = "/tags/"
  weight = 50

[[social]]
  name = "LinkedIn"
  pre = "<i class=\"fab fa-linkedin fa-2x\"></i>"
  url = "https://www.linkedin.com/in/shivam-raval-27820484/"
  weight = 10

[[social]]
  name = "GitHub"
  pre = "<i class=\"fab fa-github fa-2x\"></i>"
  url = "https://shivamvraval.github.io/"
  weight = 20

[[social]]
  name = "Instagram"
  pre = "<i class=\"fab fa-instagram fa-2x\"></i>"
  url = "https://www.instagram.com/jager.bomber/"
  weight = 30

# toml-docs-start sample-navigation
[[sample]]
  name = "Blog"
  url = "/blog/"
  weight = 10





[[sample]]
  name = "Projects"
  url = "/projects/"
  weight = 20

[[sample]]
  name = "Sample project"
  url = "/en/projects/sample-project/"
  parent = "Projects"
  weight = 1

[[sample]]
  name = "Another project"
  url = "/en/projects/another-project/"
  parent = "Projects"
  weight = 2
# toml-docs-end sample-navigation